name: Deploy Android Build to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and deploy
        run: |
          # Add your build commands here (e.g., ./gradlew assembleRelease)
          # Then deploy to Firebase App Distribution
          ./gradlew bundleRelease
          firebase appdistribution:distribute app/build/outputs/bundle/release/app-release.aab --app ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
